---
title: "Fiber-seq Analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

# Data 

* [Link](data.html)


# Co-accessibility of TFs

TF examples 

* [NRF1](TF_examples_NRF1.html)

TF Co-accessibility

* [NRF1 pairs](TF_co-acc_NRF1_pairs.html)
* [NRF1 & SP1](TF_co-acc_NRF1_SP1.html)

CpG methylation and TF binding

* [NRF1](TF_co-acc_NRF1_cpg2.html)

# Annotation for the footprints

Annotating footprints(q < 0.1) by location

* [Promoters, Pol2, OCR, original MACS footprint peaks](annotation_by_location_prompolocr.html)
* [15 states from ChromHMM, original MACS footprint peaks](annotation_by_location_ChromHMM.html)
* [Motif cluster, original MACS footprint peaks](annotation_by_location_motif_cluster.html)
* [Motif cluster, refined footprint peaks](annotation_by_location_motif_cluster_refined_peaks.html)

Determining the footprint cutoffs (p-value, q-value, fold-enrichment, pileup)

* [Link](determine_footprint_cutoffs.html)

Validating the footprints using DGF DNase footprint

* [Original MACS footprint peaks](validating_footprint_using_DNase_footprint.html)
* [Refined footprint peaks](validating_footprint_using_DNase_footprint_refinedpeaks.html)
* [Original MACS footprint peaks in FIRE](validating_footprint_using_DNase_footprint_fpinFIRE.html)

Checking the FIRE/ DNase/ ATAC-seq/ cCREs coverage for 15 states from ChromHMM

* [Base pair overlap](OCR_coverage_ChromHMM_bp.html)
* [Peak level overlap](OCR_coverage_ChromHMM_peak.html)

Checking the overlap of FIRE peaks with DNase/ ATAC-seq/ cCREs

* [Link](fire_overlap_OCRs.html)

Checking the overlap of DNase peaks with cCREs peaks

* [Link](DNase_overlap_cCREs.html)



